version: '3.4'

services:
  microorm.samples:
    image: microormsamples:dev
    container_name: MicroORM.Samples
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "MicroORM.Samples"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_microorm.samples$
    volumes:
      - C:\Source\Workspaces\MicroORM\MicroORM.Samples:/app
      - C:\Source\Workspaces\MicroORM\MicroORM:/src
      - C:\Users\andre\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_microorm.samples$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_microorm.samples$ \"/app/bin/Debug/netcoreapp3.1/MicroORM.Samples.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true